import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

import AuthProvider from '@/components/AuthProvider';
import Providers from '@/utils/provider';

const inter = Inter({ subsets: ['latin'] });

// 是所有的
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <AuthProvider>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
              <div>common layout 123</div>
              {children}
            </main>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
