import '../globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AuthProvider from '@/components/AuthProvider';
import Providers from '@/utils/provider';

const inter = Inter({ subsets: ['latin'] });

// 是所有的
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // root layout 放在 [locale] 底下，lang 才能跟著路由的 locale 走
  const { locale } = await params;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={inter.className}>
        <Providers locale={locale}>
          <AuthProvider>
            <main className='flex min-h-screen flex-col items-center justify-between p-24'>
              {children}
            </main>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
